"""add order_id to topup_requests

Revision ID: 16d0ec8d2510
Revises: c4007a1e6e43
Create Date: 2026-03-16 20:14:35.253527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d0ec8d2510'
down_revision: Union[str, Sequence[str], None] = 'c4007a1e6e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topup_requests', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topup_requests', 'vps_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topup_requests', type_='foreignkey')
    op.drop_column('topup_requests', 'order_id')
    # ### end Alembic commands ###
