"""add vps_details to vps_orders

Revision ID: 478730ff1e0b
Revises: a95456926b52
Create Date: 2026-03-17 16:43:54.290135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478730ff1e0b'
down_revision: Union[str, Sequence[str], None] = 'a95456926b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps_orders', sa.Column('vps_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps_orders', 'vps_details')
    # ### end Alembic commands ###
