"""add proof_image to topup_requests

Revision ID: 964d49579696
Revises: 16d0ec8d2510
Create Date: 2026-03-16 21:27:08.637665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964d49579696'
down_revision: Union[str, Sequence[str], None] = '16d0ec8d2510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topup_requests', sa.Column('proof_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topup_requests', 'proof_image')
    # ### end Alembic commands ###
