"""add server_type os_type to packages

Revision ID: a1d85fc923ef
Revises: 3892804eb93c
Create Date: 2026-03-15 22:42:16.954363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d85fc923ef'
down_revision: Union[str, Sequence[str], None] = '3892804eb93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps_packages', sa.Column('server_type', sa.String(), nullable=True))
    op.add_column('vps_packages', sa.Column('os_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps_packages', 'os_type')
    op.drop_column('vps_packages', 'server_type')
    # ### end Alembic commands ###
