"""add ip_type ip_address

Revision ID: bdb5bc965862
Revises: a1d85fc923ef
Create Date: 2026-03-15 23:29:51.948633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb5bc965862'
down_revision: Union[str, Sequence[str], None] = 'a1d85fc923ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps_orders', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('vps_packages', sa.Column('ip_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps_packages', 'ip_type')
    op.drop_column('vps_orders', 'ip_address')
    # ### end Alembic commands ###
